apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ .Values.identity.name }}
spec:
  type: 0
  resourceID: {{ .Values.identity.resourceId }}
  clientID: {{ .Values.identity.clientId }}
