apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.identity.name }}-binding
spec:
  azureIdentity: {{ .Values.identity.name }}
  selector: {{ .Values.identity.name }}